Modify Makefile for normal usage
Compile completed without any errors on:

macOS Sierra 10.13.1 with Command line tools installed via xcode-select --install

Common issues I found myself:

1. "make: *** No rule to make target `applet/wiring.o', needed by `applet/For'.  Stop."
--> Configure proper ARDUINO_INSTALL_DIR in Marlin/Makefile. For macOS, it was "/Applications/Arduino.app/Contents/Java"

2. "/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino/Arduino.h:257:26: fatal error: pins_arduino.h: No such file or directory
 #include "pins_arduino.h" "
--> Make sure you put right number of HARDWARE_MOTHERBOARD. It must be number unless you defined some variables(For ATMega2560 == 33)

3. "make: *** No rule to make target `applet/u8g_ll_api.o', needed by `applet/For'.  Stop."
--> Change U8GLIB value to 0. Most of character based(2004 Reprap discount one) display won't need this one. I haven't tested character one since I don't have one.

4. "/bin/sh: line 0: [: too many arguments"
--> Might be macOS Bash problems, your build full directory NEVER should contain space, eg: /home/example/The Firmware/Firmware/Marlin (X) /home/example/The_Firmware/Firmware/Marlin (O)